FROM python:3.12-slim

WORKDIR /app
COPY requirements-kafka-producer.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY arm_command_producer.py .
CMD ["python", "arm_command_producer.py"]
