FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY csv_producer.py .
COPY sample.csv /data/sample.csv

ENV CSV_PATH=/data/sample.csv

CMD ["python", "csv_producer.py"]
