"""Fictional fleet / telematics sample rows (vendor-neutral) for in-cluster CSV + S3 upload."""
from __future__ import annotations

import copy
import csv
import io
from datetime import datetime, timedelta, timezone
from typing import Any

# Columns: telematics, DTCs, geofence, trip KPIs, EV fields.
HEADER: list[str] = [
    "event_id",
    "vehicle_id",
    "fleet_id",
    "driver_id",
    "timestamp_utc",
    "latitude",
    "longitude",
    "heading_deg",
    "speed_kph",
    "odometer_km",
    "engine_rpm",
    "engine_hours",
    "fuel_level_pct",
    "fuel_rate_lph",
    "idle_time_sec",
    "active_dtcs",
    "impact_event",
    "harsh_brake",
    "harsh_accel",
    "sharp_turn",
    "harsh_cornering_g",
    "geofence_id",
    "geofence_event",
    "prestart_checklist_ok",
    "trip_id",
    "route_planned_km",
    "route_actual_km",
    "on_time_deviation_min",
    "battery_soc_pct",
    "charging_state",
    "regen_kwh",
    "notes",
]

# Baseline event rows; copied per upload and optionally re-timestamped.
FLEET_TELEMETRY_ROWS: list[dict[str, Any]] = [
    {
        "event_id": "evt-7f2a",
        "vehicle_id": "VEH-20418",
        "fleet_id": "FLEET-NORTH",
        "driver_id": "dvr-smith",
        "timestamp_utc": "2026-04-28T14:32:11Z",
        "latitude": "48.8566",
        "longitude": "2.3522",
        "heading_deg": "78",
        "speed_kph": "32.0",
        "odometer_km": "128402.3",
        "engine_rpm": "1950",
        "engine_hours": "28456.1",
        "fuel_level_pct": "64.2",
        "fuel_rate_lph": "3.1",
        "idle_time_sec": "420",
        "active_dtcs": "P0300",
        "impact_event": "false",
        "harsh_brake": "false",
        "harsh_accel": "false",
        "sharp_turn": "false",
        "harsh_cornering_g": "0.18",
        "geofence_id": "DEPOT-01",
        "geofence_event": "enter",
        "prestart_checklist_ok": "true",
        "trip_id": "trp-9c31",
        "route_planned_km": "24.0",
        "route_actual_km": "25.1",
        "on_time_deviation_min": "-4",
        "notes": "Diesel route leg; live map position",
    },
    {
        "event_id": "evt-7f2b",
        "vehicle_id": "VEH-20418",
        "fleet_id": "FLEET-NORTH",
        "driver_id": "dvr-smith",
        "timestamp_utc": "2026-04-28T14:45:22Z",
        "latitude": "48.8601",
        "longitude": "2.3604",
        "heading_deg": "80",
        "speed_kph": "0.0",
        "odometer_km": "128412.0",
        "engine_rpm": "800",
        "engine_hours": "28456.4",
        "fuel_level_pct": "63.0",
        "fuel_rate_lph": "0.0",
        "idle_time_sec": "1280",
        "impact_event": "false",
        "harsh_brake": "false",
        "harsh_accel": "false",
        "sharp_turn": "false",
        "harsh_cornering_g": "0.09",
        "geofence_event": "exit",
        "prestart_checklist_ok": "true",
        "trip_id": "trp-9c31",
        "route_planned_km": "24.0",
        "route_actual_km": "25.1",
        "on_time_deviation_min": "-4",
        "notes": "Yard idle before dock",
    },
    {
        "event_id": "evt-7f2c",
        "vehicle_id": "VEH-19881",
        "fleet_id": "FLEET-SOUTH",
        "driver_id": "dvr-lee",
        "timestamp_utc": "2026-04-28T14:50:01Z",
        "latitude": "43.6108",
        "longitude": "3.8772",
        "heading_deg": "12",
        "speed_kph": "0.0",
        "odometer_km": "87221.0",
        "engine_rpm": "0",
        "engine_hours": "12033.0",
        "fuel_level_pct": "0.0",
        "fuel_rate_lph": "0.0",
        "idle_time_sec": "0",
        "impact_event": "false",
        "harsh_brake": "false",
        "harsh_accel": "false",
        "sharp_turn": "false",
        "harsh_cornering_g": "0.00",
        "geofence_event": "exit",
        "prestart_checklist_ok": "true",
        "trip_id": "trp-8b02",
        "route_planned_km": "0.0",
        "route_actual_km": "0.0",
        "on_time_deviation_min": "0",
        "battery_soc_pct": "82.0",
        "charging_state": "plugged",
        "regen_kwh": "2.1",
        "notes": "EV overnight top-up at depot",
    },
    {
        "event_id": "evt-7f2d",
        "vehicle_id": "VEH-19881",
        "fleet_id": "FLEET-SOUTH",
        "driver_id": "dvr-lee",
        "timestamp_utc": "2026-04-28T15:10:14Z",
        "latitude": "43.6089",
        "longitude": "3.8755",
        "heading_deg": "95",
        "speed_kph": "0.0",
        "odometer_km": "87221.0",
        "engine_rpm": "0",
        "engine_hours": "12033.0",
        "fuel_level_pct": "0.0",
        "fuel_rate_lph": "0.0",
        "idle_time_sec": "0",
        "impact_event": "false",
        "harsh_brake": "false",
        "harsh_accel": "false",
        "sharp_turn": "false",
        "harsh_cornering_g": "0.00",
        "geofence_id": "WHSE-A",
        "geofence_event": "enter",
        "prestart_checklist_ok": "true",
        "trip_id": "trp-8b10",
        "route_planned_km": "0.0",
        "route_actual_km": "0.0",
        "on_time_deviation_min": "0",
        "battery_soc_pct": "91.0",
        "charging_state": "not_charging",
        "regen_kwh": "0.0",
        "notes": "EV dispatch prep inside geofence",
    },
    {
        "event_id": "evt-7f2e",
        "vehicle_id": "VEH-20105",
        "fleet_id": "FLEET-CENTRAL",
        "driver_id": "dvr-patel",
        "timestamp_utc": "2026-04-28T15:12:40Z",
        "latitude": "51.5074",
        "longitude": "-0.1278",
        "heading_deg": "210",
        "speed_kph": "45.0",
        "odometer_km": "201883.0",
        "engine_rpm": "1950",
        "engine_hours": "41022.0",
        "fuel_level_pct": "38.0",
        "fuel_rate_lph": "4.0",
        "idle_time_sec": "0",
        "active_dtcs": "P0420;P0171",
        "impact_event": "false",
        "harsh_brake": "false",
        "harsh_accel": "false",
        "sharp_turn": "false",
        "harsh_cornering_g": "0.22",
        "geofence_id": "WHSE-C",
        "geofence_event": "enter",
        "prestart_checklist_ok": "false",
        "trip_id": "trp-7a44",
        "route_planned_km": "18.0",
        "route_actual_km": "19.2",
        "on_time_deviation_min": "3",
        "notes": "Catalyst efficiency warning and lean condition",
    },
    {
        "event_id": "evt-7f2f",
        "vehicle_id": "VEH-20105",
        "fleet_id": "FLEET-CENTRAL",
        "driver_id": "dvr-patel",
        "timestamp_utc": "2026-04-28T15:19:22Z",
        "latitude": "51.5030",
        "longitude": "-0.1201",
        "heading_deg": "200",
        "speed_kph": "0.0",
        "odometer_km": "201891.0",
        "engine_rpm": "0",
        "engine_hours": "41022.3",
        "fuel_level_pct": "35.0",
        "fuel_rate_lph": "0.0",
        "idle_time_sec": "0",
        "impact_event": "false",
        "harsh_brake": "true",
        "harsh_accel": "false",
        "sharp_turn": "false",
        "harsh_cornering_g": "0.31",
        "geofence_event": "exit",
        "prestart_checklist_ok": "false",
        "trip_id": "trp-7a44",
        "route_planned_km": "18.0",
        "route_actual_km": "19.2",
        "on_time_deviation_min": "3",
        "notes": "Harsh deceleration near warehouse gate",
    },
    {
        "event_id": "evt-7f30",
        "vehicle_id": "VEH-20105",
        "fleet_id": "FLEET-CENTRAL",
        "driver_id": "dvr-patel",
        "timestamp_utc": "2026-04-28T15:20:00Z",
        "latitude": "51.5012",
        "longitude": "-0.1155",
        "heading_deg": "5",
        "speed_kph": "0.0",
        "odometer_km": "201891.0",
        "engine_rpm": "0",
        "engine_hours": "41022.3",
        "fuel_level_pct": "35.0",
        "fuel_rate_lph": "0.0",
        "idle_time_sec": "300",
        "impact_event": "true",
        "harsh_brake": "false",
        "harsh_accel": "false",
        "sharp_turn": "false",
        "harsh_cornering_g": "0.00",
        "geofence_event": "enter",
        "prestart_checklist_ok": "false",
        "trip_id": "trp-7a44",
        "route_planned_km": "18.0",
        "route_actual_km": "19.2",
        "on_time_deviation_min": "3",
        "notes": "Impact sensor threshold crossed; dispatch notified",
    },
    {
        "event_id": "evt-7f31",
        "vehicle_id": "VEH-19502",
        "fleet_id": "FLEET-CENTRAL",
        "driver_id": "dvr-kim",
        "timestamp_utc": "2026-04-28T16:01:00Z",
        "latitude": "52.5200",
        "longitude": "-1.9000",
        "heading_deg": "130",
        "speed_kph": "0.0",
        "odometer_km": "99004.0",
        "engine_rpm": "0",
        "engine_hours": "0.0",
        "fuel_level_pct": "0.0",
        "fuel_rate_lph": "0.0",
        "idle_time_sec": "0",
        "impact_event": "false",
        "harsh_brake": "false",
        "harsh_accel": "false",
        "sharp_turn": "false",
        "harsh_cornering_g": "0.00",
        "geofence_id": "MAINT-01",
        "geofence_event": "enter",
        "prestart_checklist_ok": "true",
        "trip_id": "trp-0x00",
        "route_planned_km": "0.0",
        "route_actual_km": "0.0",
        "on_time_deviation_min": "0",
        "notes": "Scheduled service: oil and brakes",
    },
]


def _iso_utc_z(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")


def build_fleet_csv_bytes(
    *,
    bump_timestamps: bool = True,
    upload_cycle: int = 0,
) -> bytes:
    """
    Build UTF-8 CSV in memory. When bump_timestamps is True, event times are
    re-staggered from "now" so each upload is unique (new S3 ETag) for the consumer.
    """
    rows: list[dict[str, Any]] = [copy.deepcopy(r) for r in FLEET_TELEMETRY_ROWS]
    if bump_timestamps:
        base = datetime.now(timezone.utc)
        for i, row in enumerate(rows):
            row["timestamp_utc"] = _iso_utc_z(base + timedelta(seconds=i))
    if upload_cycle and rows:
        extra = f" [upload_cycle={upload_cycle}]"
        notes = (rows[-1].get("notes") or "") + extra
        rows[-1]["notes"] = notes.strip()
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(HEADER)
    for row in rows:
        writer.writerow([str(row.get(c, "")) for c in HEADER])
    return buffer.getvalue().encode("utf-8")
